name: blockchain_wallet
description: A blockchain wallet developed with flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_riverpod: ^2.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono/RobotoMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono/RobotoMono-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
    - family: MicrosoftJhengHei
      fonts:
        - asset: assets/fonts/MicrosoftJhengHei/MicrosoftJhengHei-Bold.ttf
          weight: 700
        - asset: assets/fonts/MicrosoftJhengHei/MicrosoftJhengHei-Regular.ttf
          weight: 400
    # - family: BWIcons
    #   fonts:
    #     - asset: assets/fonts/BWIcons.ttf

flutter_intl:
  enabled: true